packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  less: true
  prisma: true
  sharp: true
  unrs-resolver: true
